### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by ssured** [ciena-frost/bunsen-tutorial#12]
Hi, 
first of all, thanks for open sourcing your work. It's inspiring and generally awesome. The tutorial is easy to follow and gives a nice insight into the code.

While reviewing I saw this lib includes Redux, but to me it is not visible how this works and how to benefit from the inclusion. Maybe you can add some text about why it is included and how it should be used (for instance for undo/redo)

Thanks!

**Comment by sandersky** [comment]
Currently redux is being used internally in `ember-frost-bunsen` to manage the state of the form. It is not exposed to the consumer and undo/redo functionality has not been considered although it may not be difficult to add.

**Comment by ssured** [comment]
Thanks for detailing this!
